function getDomRefs() {
  const authForm = document.getElementById("authForm");
  return {
    toastContainer: document.getElementById("toastContainer"),
    appRoot: document.getElementById("appRoot"),
    startupLoader: document.getElementById("startupLoader"),
    authForm,
    authPanel: document.getElementById("authPanel"),
    settingsBackdrop: document.getElementById("settingsBackdrop"),
    settingsButton: document.getElementById("settingsButton"),
    closeSettingsButton: document.getElementById("closeSettingsButton"),
    authEmail: document.getElementById("authEmail"),
    authPassword: document.getElementById("authPassword"),
    authStatus: document.getElementById("authStatus"),
    authLoading: document.getElementById("authLoading"),
    authLoadingText: document.getElementById("authLoadingText"),
    appStatus: document.getElementById("appStatus"),
    signInButton: document.getElementById("signInButton"),
    signUpButton: document.getElementById("signUpButton"),
    themeToggleButton: document.getElementById("themeToggleButton"),
    signedInEmail: document.getElementById("signedInEmail"),
    signOutButton: document.getElementById("signOutButton"),
    authConfirmPassword: document.getElementById("authConfirmPassword"),
    authConfirmPasswordLabel: authForm?.querySelector('label[for="authConfirmPassword"]'),
    passwordRequirements: document.getElementById("passwordRequirements"),
    authEmailLabel: authForm?.querySelector('label[for="authEmail"]'),
    authPasswordLabel: authForm?.querySelector('label[for="authPassword"]'),
    recipeForm: document.getElementById("recipeForm"),
    recipeListLoading: document.getElementById("recipeListLoading"),
    recipeList: document.getElementById("recipeList"),
    searchInput: document.getElementById("searchInput"),
    categoryFilter: document.getElementById("categoryFilter"),
    favouritesFilter: document.getElementById("favouritesFilter"),
    sortSelect: document.getElementById("sortSelect"),
    searchPanel: document.querySelector(".panel--search"),
    listPanel: document.querySelector(".panel--list"),
    addRecipeSection: document.getElementById("addRecipeSection"),
    recipeFormHeading: document.getElementById("recipeFormHeading"),
    toggleAddRecipe: document.getElementById("toggleAddRecipe"),
    saveRecipeButton: document.getElementById("saveRecipeButton"),
    cancelEditButton: document.getElementById("cancelEditButton"),
    imageInput: document.getElementById("image"),
    imageUrlInput: document.getElementById("imageUrlInput"),
    recipeImportUrlInput: document.getElementById("recipeImportUrl"),
    importRecipeButton: document.getElementById("importRecipeButton"),
    recipeImportPromptInput: document.getElementById("recipeImportPrompt"),
    resetImportPromptButton: document.getElementById("resetImportPromptButton"),
    prepHoursInput: document.getElementById("prepHours"),
    prepMinutesInput: document.getElementById("prepMinutes"),
    prepTimeWarning: document.getElementById("prepTimeWarning"),
    cookHoursInput: document.getElementById("cookHours"),
    cookMinutesInput: document.getElementById("cookMinutes"),
    cookTimeWarning: document.getElementById("cookTimeWarning"),
    totalTimeInput: document.getElementById("totalTime"),
    servesInput: document.getElementById("serves"),
    servesWarning: document.getElementById("servesWarning"),
    difficultyInput: document.getElementById("difficulty"),
    difficultyValue: document.getElementById("difficultyValue"),
    editImageTools: document.getElementById("editImageTools"),
    editImagePreview: document.getElementById("editImagePreview"),
    editImageEmpty: document.getElementById("editImageEmpty"),
    chooseImageButton: document.getElementById("chooseImageButton"),
    clearImageButton: document.getElementById("clearImageButton"),
    undoImageButton: document.getElementById("undoImageButton"),
    recipeDetail: document.getElementById("recipeDetail"),
    detailContent: document.getElementById("detailContent"),
    closeDetail: document.getElementById("closeDetail"),
    addButtonWideQuery: window.matchMedia("(min-width: 768px)")
  };
}

window.StorecipeDomRefs = {
  getDomRefs
};
